return {
  {"assistance", "Assistance"},
  {"origin", "Origin"},
  {"furious", "Furious"},
  {"nameless", "Nameless"},
  {"rival", "Rival"},
  {"event2years", "2 Years"},
  {"fable", "Fable"},
  {"competitive", "Competitive"},
  {"halloween_2019", "Halloween 2019"},
  {"newyear2020", "New Year 2020"},
  {"scorpion", "Scorpion"},
  {"project_z9", "Project Z9"},
  {"rainbow", "Rainbow"},
  {"revival", "Revival"},
  {"halloween_2020", "Halloween 2020"},
  {"new_year_2021", "New Year 2021"},
  {"travelers_bag", "Traveller's bag"},
  {"event4years", "4 Years"},
  {"empire", "Empire"},
  {"dragon_rise", "Dragon Rise"},
  {"cursed_souls", "Cursed Souls"},
  {"winter_fun_2022", "Winter Fun 2022"},
  {"event5years", "5 Years"},
  {"sharp", "Sharp"},
  {"legends", "Legends"},
  {"project_pandora", "Project Pandora"},
  {"splash", "Splash"},
  {"hot_winter_party_2023", "Hot Winter Party 2023"},
  {"standoff_2", "Standoff 2"},
  {"fireborn", "Fireborn"},
  {"revenge", "Revenge"},
  {"space_vision", "Space Vision"},
  {"sunstrike", "Sunstrike"},
  {"flow", "Flow"},
  {"subjectx", "Subject X"},
  {"frosty_chaos", "Frosty Chaos"},
  {"shine", "Shine"},
  {"outcast", "Outcast"},
  {"chameleon", "Chameleon"},
  {"fun_and_sun", "FUN&SUN"},
  {"reforged", "Reforged"},
  {"vibe", "Vibe"},
  {"nightmare", "Nightmare"},
  {"collaboration", "Collaboration"},
  {"major2024", "Esports"},
  {"kitsune_dreams", "Kitsune Dreams"},
  {"joy", "Joy"},
  {"prey", "Prey"},
  {"dynasty", "Dynasty"},
  {"event8years", "8 Years"},
  {"gambit", "Gambit"},
  {"syndicate", "Syndicate"},
  {"rewind", "Rewind"},
  {"dia_de_muertos", "Dia de Muertos"},
}
